### ISSUE TITLE
Safari support?

### ISSUE THREAD

**Issue by chuprik** [eligrey/async-document-write#1]
hi!

I have this error:

```
TypeError: undefined is not an object (evaluating 'loc.replace')
```

I did small investigate and found next:

```
TypeError: 0 is not a function. (In '0()', '0' is 0)
```

I'm not sure, but this means that `async-document-write` doesn't supports Safari?

**Comment by eligrey** [comment]
I need to update the script location finder as browsers have recently updated the method of locating the current script location. I'll update it soon. Remind me in 1 week if I forget.

**Comment by eligrey** [comment]
Basically I'll need to use `(document.currentScript || document.scripts[document.scripts.length-1]).src`

**Comment by chuprik** [comment]
hmmm, let me check this solution. because I need this now :smile:

**Comment by eligrey** [comment]
@kotchuprik it should work for you now.
